import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { AuthContext } from "../src/context/auth-context";

export default function Home() {
  const router = useRouter();
  const authContext = React.useContext(AuthContext);

  console.log(router.query);

  React.useEffect(() => {
    // checks if the user is authenticated
    authContext.isUserAuthenticated!()
      ? router.push("/home")
      : router.push("/");
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         <span className={styles.blue}>You are Logged in to Dashboard</span>
        </h1>

        <p className={styles.description}>
          Logout by <Link href="/logout">this link</Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
}
