import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";
import { AuthContext, AuthData } from "../src/context/auth-context";
import styles from "../styles/Home.module.css";

// Check token

export default function Home() {
  const router = useRouter();
  const authContext = React.useContext(AuthContext);
  const timeoutBeforeRedirect = 2000;
  
  // if (router.query && router.query.token) {
  //   const authData: AuthData = { token: router.query.token.toString()};
  //   authContext.setAuthState!(authData);
  //   console.log( authContext.isUserAuthenticated!(),'dfd');
  // }

  React.useEffect(() => {
    if (router.query && router.query.token) {
      console.log( { token: router.query.token.toString()})
      const authData: AuthData = { token: router.query.token.toString()};
      authContext.setAuthState!(authData);
      setTimeout(() => {
        router.push("/home");

      }, timeoutBeforeRedirect);
    } else {

      const initialAuthData: AuthData = { token: localStorage.getItem("token") ?? ""};
      authContext.setAuthState!(initialAuthData);
    }
    // authContext.isUserAuthenticated!()
    // ? router.push("/home")
    // : router.push("/");
    // checks if the user is authenticated
    // authContext.isUserAuthenticated!()
    //   ? router.push("/home")
    //   : router.push("/");
  }, [router]); 

  return (
    <div className={styles.container}>
      <Head>
        <title>Checking authentication</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home Page
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>Checking our auth code...</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </div>
  );
}
